# http://localhost:3001/


# POST http://localhost:3001/users
# Content-Type: application/json  

# {
#   "name": "John Doe 1",
#   "email": "pawankumar@gmail.com"
# }

# GET http://localhost:3001/users